### ISSUE TITLE
safe: boolean should default to true

### ISSUE THREAD

**Issue by torusJKL** [MerlinB/planter#2]
With the Genesis upgrade the default of the boolean should be set to true.
Otherwise the OP_RETURN script will be interpreted as a hash puzzle.

**Comment by MerlinB** [comment]
My reasoning before was that the mom planaria endpoint didn't support OP_FALSE. I just rechecked and it seems to work. I'll change the default, thanks.

**Comment by MerlinB** [comment]
Thanks for the PR, merged.
